### ISSUE TITLE
News don't working

### ISSUE THREAD

**Issue by imidsac** [refinery/refinerycms-news#161]
```ruby
ActionView::Template::Error (No route matches {:action=>"index", :controller=>"refinery/news/items", :locale=>:fr}):
    24:     <div class="info col-md-8 col-sm-8">
    25:       <ul class="menu-top navbar-right hidden-xs">
    26:         <% ::Refinery::I18n.frontend_locales.each do |locale| %>
    27:             <li><%= link_to_if Globalize.locale.to_s != locale.to_s, locale, {:locale => locale} %></li>
    28:         <% end %>
    29:       </ul><!--//menu-top-->
    30:       <br />
  app/views/refinery/_header.html.erb:27:in `block in _app_views_refinery__header_html_erb___18377456877475543_70156724610900'
  app/views/refinery/_header.html.erb:26:in `each'
  app/views/refinery/_header.html.erb:26:in `_app_views_refinery__header_html_erb___18377456877475543_70156724610900'
  app/views/layouts/application.html.erb:9:in `_app_views_layouts_application_html_erb___352687323920669255_70156750564900'
```

**Comment by bricesanchez** [comment]
Could you copy/paste your Gemfile.lock ?

**Comment by imidsac** [comment]
source 'https://rubygems.org'
ruby '2.2.3'

# Bundle edge Rails instead: gem 'rails', github: 'rails/rails'
gem 'rails', '~> 4.2.4'

# Use PostgreSQL as the database for Active Record
gem 'pg'

gem 'therubyracer', '~> 0.12.1', :require => 'v8'

gem 'bootstrap-sass', '~> 3.3.5'
gem 'font-awesome-rails'

# Use SCSS for stylesheets
gem 'sass-rails', '~> 5.0'
# Use Uglifier as compressor for JavaScript assets
gem 'uglifier', '>= 1.3.0'
# Use CoffeeScript for .coffee assets and views
gem 'coffee-rails', '~> 4.1.0'
# See https://github.com/rails/execjs#readme for more supported runtimes
# gem 'therubyracer', platforms: :ruby

# Use jquery as the JavaScript library
gem 'jquery-rails'
gem 'jquery-turbolinks'

# Turbolinks makes following links in your web application faster. Read more: https://github.com/rails/turbolinks
gem 'turbolinks'
# Build JSON APIs with ease. Read more: https://github.com/rails/jbuilder
gem 'jbuilder', '~> 2.0'
# bundle exec rake doc:rails generates the API under doc/api.
gem 'sdoc', '~> 0.4.0', group: :doc

# Use ActiveModel has_secure_password
# gem 'bcrypt', '~> 3.1.7'

# Use Unicorn as the app server
gem 'unicorn'

# Use Capistrano for deployment
# gem 'capistrano-rails', group: :development

group :development, :test do
  # Call 'byebug' anywhere in the code to stop execution and get a debugger console
  gem 'byebug'
end

group :development do
  # Access an IRB console on exception pages or by using <%= console %> in views
  gem 'web-console', '~> 2.0'

  # Spring speeds up development by keeping your application running in the background. Read more: https://github.com/rails/spring
  gem 'spring'

  gem 'quiet_assets'
  gem 'letter_opener'
  gem 'sextant'
  gem 'guard', '>= 2.2.2',       :require => false
  gem 'guard-livereload',        :require => false
  gem 'rack-livereload'
  gem 'rb-fsevent',              :require => false
  gem 'figaro'
end

group :production do
  # Heroku
  gem 'dragonfly-s3_data_store'
  gem 'rails_12factor'
  gem 'rails_on_heroku'
  gem 'heroku-deflater'
  gem 'whenever', :require => false

  # Caching strategy
  gem 'actionpack-page_caching'
  gem 'rack-cache'
  gem 'kgio'
  gem 'dalli'
  gem 'memcachier'
end


gem 'refinerycms', git: 'https://github.com/refinery/refinerycms', branch: 'master'

# Add support for searching inside Refinery's admin interface.
gem 'refinerycms-acts-as-indexed', ['~> 2.0', '>= 2.0.0']

# Add support for Refinery's custom fork of the visual editor WYMeditor.
gem 'refinerycms-wymeditor', ['~> 1.0', '>= 1.0.6']

# The default authentication adapter
gem 'refinerycms-authentication-devise', '~> 1.0'

# gem 'refinerycms-blog', github: 'refinery/refinerycms-blog', branch: 'master'
#
# gem 'seo_meta', git: 'https://github.com/parndt/seo_meta', branch: 'master'
#
# gem 'paper_trail', git: 'https://github.com/airblade/paper_trail', branch: 'master'
#
# gem 'refinerycms-settings', github: 'refinery/refinerycms-settings', branch: 'master'
# gem 'refinerycms-page-images', github: 'refinery/refinerycms-page-images', branch: 'master'
#
# gem 'refinerycms-testing', git: 'https://github.com/refinery/refinerycms', branch: 'master'

gem 'paperclip'
gem 'aws-sdk', '>= 2.0.0'
gem 'fog'
#gem 'figaro'

 #gem 'globalize3'
 gem 'unf'
 gem 'asset_sync'

gem 'refinerycms-news', github: 'refinery/refinerycms-news', branch: 'master'
#gem 'refinerycms-events', '= 0.1', :require => 'events', :git => 'git://github.com/Vizzuality/refinerycms-events.git'
#gem "refinerycms-settings", git: "https://github.com/refinery/refinerycms-settings", branch: "master"

**Comment by imidsac** [comment]
GIT
  remote: git://github.com/refinery/refinerycms-news.git
  revision: 615f828eb7fc24c6ad9ade484d5af2294f02a79c
  branch: master
  specs:
    refinerycms-news (3.0.0)
      acts_as_indexed (~> 0.8.0)
      friendly_id (~> 5.1.0)
      globalize (>= 4.0.0, < 5.2)
      refinerycms-core (~> 3.0.0)
      refinerycms-settings (~> 3.0.0)

GIT
  remote: https://github.com/refinery/refinerycms
  revision: 1d13007ffe55e2f0aa9c3911be31df0b854cfbd0
  branch: master
  specs:
    refinerycms (3.0.0)
      refinerycms-core (= 3.0.0)
      refinerycms-images (= 3.0.0)
      refinerycms-pages (= 3.0.0)
      refinerycms-resources (= 3.0.0)
    refinerycms-core (3.0.0)
      actionpack (>= 4.2.3, < 5.0)
      activerecord (>= 4.2.3, < 5.0)
      awesome_nested_set (~> 3.0.0)
      coffee-rails (~> 4.0, >= 4.0.0)
      decorators (~> 2.0.0)
      jquery-rails (>= 2.3.0)
      jquery-ui-rails (~> 5.0.0)
      railties (>= 4.2.3, < 5.0)
      refinerycms-i18n (~> 3.0.0)
      sass-rails (>= 4.0, < 5.1)
      truncate_html (~> 0.9)
      will_paginate (~> 3.0.2)
      zilch-authorisation
    refinerycms-images (3.0.0)
      dragonfly (~> 1.0.0)
      globalize (>= 4.0.0, < 5.2)
      refinerycms-core (= 3.0.0)
    refinerycms-pages (3.0.0)
      awesome_nested_set (~> 3.0.0)
      babosa (!= 0.3.6)
      friendly_id (~> 5.1.0)
      globalize (>= 4.0.0, < 5.2)
      refinerycms-core (= 3.0.0)
      seo_meta (~> 2.0.0.rc.1)
      speakingurl-rails (~> 1.1.2)
    refinerycms-resources (3.0.0)
      acts_as_indexed (~> 0.8.0)
      dragonfly (~> 1.0.0)
      globalize (>= 4.0.0, < 5.2)
      refinerycms-core (= 3.0.0)

GEM
  remote: https://rubygems.org/
  specs:
    CFPropertyList (2.3.2)
    actionmailer (4.2.5)
      actionpack (= 4.2.5)
      actionview (= 4.2.5)
      activejob (= 4.2.5)
      mail (~> 2.5, >= 2.5.4)
      rails-dom-testing (~> 1.0, >= 1.0.5)
    actionpack (4.2.5)
      actionview (= 4.2.5)
      activesupport (= 4.2.5)
      rack (~> 1.6)
      rack-test (~> 0.6.2)
      rails-dom-testing (~> 1.0, >= 1.0.5)
      rails-html-sanitizer (~> 1.0, >= 1.0.2)
    actionpack-page_caching (1.0.2)
      actionpack (>= 4.0.0, < 5)
    actionview (4.2.5)
      activesupport (= 4.2.5)
      builder (~> 3.1)
      erubis (~> 2.7.0)
      rails-dom-testing (~> 1.0, >= 1.0.5)
      rails-html-sanitizer (~> 1.0, >= 1.0.2)
    activejob (4.2.5)
      activesupport (= 4.2.5)
      globalid (>= 0.3.0)
    activemodel (4.2.5)
      activesupport (= 4.2.5)
      builder (~> 3.1)
    activerecord (4.2.5)
      activemodel (= 4.2.5)
      activesupport (= 4.2.5)
      arel (~> 6.0)
    activesupport (4.2.5)
      i18n (~> 0.7)
      json (~> 1.7, >= 1.7.7)
      minitest (~> 5.1)
      thread_safe (~> 0.3, >= 0.3.4)
      tzinfo (~> 1.1)
    acts_as_indexed (0.8.3)
    addressable (2.4.0)
    arel (6.0.3)
    asset_sync (1.1.0)
      activemodel
      fog (>= 1.8.0)
      unf
    autoprefixer-rails (6.1.2)
      execjs
      json
    awesome_nested_set (3.0.2)
      activerecord (>= 4.0.0, < 5)
    aws-sdk (2.2.5)
      aws-sdk-resources (= 2.2.5)
    aws-sdk-core (2.2.5)
      jmespath (~> 1.0)
    aws-sdk-resources (2.2.5)
      aws-sdk-core (= 2.2.5)
    babosa (1.0.2)
    bcrypt (3.1.10)
    binding_of_caller (0.7.2)
      debug_inspector (>= 0.0.1)
    bootstrap-sass (3.3.6)
      autoprefixer-rails (>= 5.2.1)
      sass (>= 3.3.4)
    builder (3.2.2)
    byebug (8.2.1)
    chronic (0.10.2)
    climate_control (0.0.3)
      activesupport (>= 3.0)
    cocaine (0.5.8)
      climate_control (>= 0.0.3, < 1.0)
    coderay (1.1.0)
    coffee-rails (4.1.0)
      coffee-script (>= 2.2.0)
      railties (>= 4.0.0, < 5.0)
    coffee-script (2.4.1)
      coffee-script-source
      execjs
    coffee-script-source (1.10.0)
    concurrent-ruby (1.0.0)
    dalli (2.7.4)
    debug_inspector (0.0.2)
    decorators (2.0.1)
      railties (>= 4.0.0, < 5.0.0)
    devise (3.5.2)
      bcrypt (~> 3.0)
      orm_adapter (~> 0.1)
      railties (>= 3.2.6, < 5)
      responders
      thread_safe (~> 0.1)
      warden (~> 1.2.3)
    dragonfly (1.0.12)
      addressable (~> 2.3)
      multi_json (~> 1.0)
      rack (>= 1.3.0)
    dragonfly-s3_data_store (1.2)
      dragonfly (~> 1.0)
      fog-aws
    em-websocket (0.5.1)
      eventmachine (>= 0.12.9)
      http_parser.rb (~> 0.6.0)
    erubis (2.7.0)
    eventmachine (1.0.8)
    excon (0.45.4)
    execjs (2.6.0)
    ffi (1.9.10)
    figaro (1.1.1)
      thor (~> 0.14)
    fission (0.5.0)
      CFPropertyList (~> 2.2)
    fog (1.36.0)
      fog-aliyun (>= 0.1.0)
      fog-atmos
      fog-aws (>= 0.6.0)
      fog-brightbox (~> 0.4)
      fog-core (~> 1.32)
      fog-dynect (~> 0.0.2)
      fog-ecloud (~> 0.1)
      fog-google (<= 0.1.0)
      fog-json
      fog-local
      fog-powerdns (>= 0.1.1)
      fog-profitbricks
      fog-radosgw (>= 0.0.2)
      fog-riakcs
      fog-sakuracloud (>= 0.0.4)
      fog-serverlove
      fog-softlayer
      fog-storm_on_demand
      fog-terremark
      fog-vmfusion
      fog-voxel
      fog-xenserver
      fog-xml (~> 0.1.1)
      ipaddress (~> 0.5)
      nokogiri (~> 1.5, >= 1.5.11)
    fog-aliyun (0.1.0)
      fog-core (~> 1.27)
      fog-json (~> 1.0)
      ipaddress (~> 0.8)
      xml-simple (~> 1.1)
    fog-atmos (0.1.0)
      fog-core
      fog-xml
    fog-aws (0.7.6)
      fog-core (~> 1.27)
      fog-json (~> 1.0)
      fog-xml (~> 0.1)
      ipaddress (~> 0.8)
    fog-brightbox (0.10.1)
      fog-core (~> 1.22)
      fog-json
      inflecto (~> 0.0.2)
    fog-core (1.35.0)
      builder
      excon (~> 0.45)
      formatador (~> 0.2)
    fog-dynect (0.0.2)
      fog-core
      fog-json
      fog-xml
    fog-ecloud (0.3.0)
      fog-core
      fog-xml
    fog-google (0.1.0)
      fog-core
      fog-json
      fog-xml
    fog-json (1.0.2)
      fog-core (~> 1.0)
      multi_json (~> 1.10)
    fog-local (0.2.1)
      fog-core (~> 1.27)
    fog-powerdns (0.1.1)
      fog-core (~> 1.27)
      fog-json (~> 1.0)
      fog-xml (~> 0.1)
    fog-profitbricks (0.0.5)
      fog-core
      fog-xml
      nokogiri
    fog-radosgw (0.0.4)
      fog-core (>= 1.21.0)
      fog-json
      fog-xml (>= 0.0.1)
    fog-riakcs (0.1.0)
      fog-core
      fog-json
      fog-xml
    fog-sakuracloud (1.5.0)
      fog-core
      fog-json
    fog-serverlove (0.1.2)
      fog-core
      fog-json
    fog-softlayer (1.0.2)
      fog-core
      fog-json
    fog-storm_on_demand (0.1.1)
      fog-core
      fog-json
    fog-terremark (0.1.0)
      fog-core
      fog-xml
    fog-vmfusion (0.1.0)
      fission
      fog-core
    fog-voxel (0.1.0)
      fog-core
      fog-xml
    fog-xenserver (0.2.2)
      fog-core
      fog-xml
    fog-xml (0.1.2)
      fog-core
      nokogiri (~> 1.5, >= 1.5.11)
    font-awesome-rails (4.5.0.0)
      railties (>= 3.2, < 5.0)
    formatador (0.2.5)
    friendly_id (5.1.0)
      activerecord (>= 4.0.0)
    globalid (0.3.6)
      activesupport (>= 4.1.0)
    globalize (5.0.1)
      activemodel (>= 4.2.0, < 4.3)
      activerecord (>= 4.2.0, < 4.3)
    guard (2.13.0)
      formatador (>= 0.2.4)
      listen (>= 2.7, <= 4.0)
      lumberjack (~> 1.0)
      nenv (~> 0.1)
      notiffany (~> 0.0)
      pry (>= 0.9.12)
      shellany (~> 0.0)
      thor (>= 0.18.1)
    guard-compat (1.2.1)
    guard-livereload (2.5.1)
      em-websocket (~> 0.5)
      guard (~> 2.8)
      guard-compat (~> 1.0)
      multi_json (~> 1.8)
    heroku-deflater (0.6.2)
      rack (>= 1.4.5)
    http_parser.rb (0.6.0)
    i18n (0.7.0)
    inflecto (0.0.2)
    ipaddress (0.8.0)
    jbuilder (2.3.2)
      activesupport (>= 3.0.0, < 5)
      multi_json (~> 1.2)
    jmespath (1.1.3)
    jquery-rails (4.0.5)
      rails-dom-testing (~> 1.0)
      railties (>= 4.2.0)
      thor (>= 0.14, < 2.0)
    jquery-turbolinks (2.1.0)
      railties (>= 3.1.0)
      turbolinks
    jquery-ui-rails (5.0.5)
      railties (>= 3.2.16)
    json (1.8.3)
    kgio (2.10.0)
    launchy (2.4.3)
      addressable (~> 2.3)
    letter_opener (1.4.1)
      launchy (~> 2.2)
    libv8 (3.16.14.13)
    listen (3.0.5)
      rb-fsevent (>= 0.9.3)
      rb-inotify (>= 0.9)
    loofah (2.0.3)
      nokogiri (>= 1.5.9)
    lumberjack (1.0.9)
    mail (2.6.3)
      mime-types (>= 1.16, < 3)
    memcachier (0.0.2)
    method_source (0.8.2)
    mime-types (2.99)
    mimemagic (0.3.0)
    mini_portile2 (2.0.0)
    minitest (5.8.3)
    multi_json (1.11.2)
    nenv (0.2.0)
    nokogiri (1.6.7)
      mini_portile2 (~> 2.0.0.rc2)
    notiffany (0.0.8)
      nenv (~> 0.1)
      shellany (~> 0.0)
    orm_adapter (0.5.0)
    paperclip (4.3.2)
      activemodel (>= 3.2.0)
      activesupport (>= 3.2.0)
      cocaine (~> 0.5.5)
      mime-types
      mimemagic (= 0.3.0)
    pg (0.18.4)
    pry (0.10.3)
      coderay (~> 1.1.0)
      method_source (~> 0.8.1)
      slop (~> 3.4)
    quiet_assets (1.1.0)
      railties (>= 3.1, < 5.0)
    rack (1.6.4)
    rack-cache (1.5.1)
      rack (>= 0.4)
    rack-livereload (0.3.16)
      rack
    rack-test (0.6.3)
      rack (>= 1.0)
    rails (4.2.5)
      actionmailer (= 4.2.5)
      actionpack (= 4.2.5)
      actionview (= 4.2.5)
      activejob (= 4.2.5)
      activemodel (= 4.2.5)
      activerecord (= 4.2.5)
      activesupport (= 4.2.5)
      bundler (>= 1.3.0, < 2.0)
      railties (= 4.2.5)
      sprockets-rails
    rails-deprecated_sanitizer (1.0.3)
      activesupport (>= 4.2.0.alpha)
    rails-dom-testing (1.0.7)
      activesupport (>= 4.2.0.beta, < 5.0)
      nokogiri (~> 1.6.0)
      rails-deprecated_sanitizer (>= 1.0.1)
    rails-html-sanitizer (1.0.2)
      loofah (~> 2.0)
    rails-i18n (4.0.7)
      i18n (~> 0.7)
      railties (~> 4.0)
    rails_12factor (0.0.3)
      rails_serve_static_assets
      rails_stdout_logging
    rails_on_heroku (0.0.2)
      rails_serve_static_assets
      rails_stdout_logging
    rails_serve_static_assets (0.0.4)
    rails_stdout_logging (0.0.4)
    railties (4.2.5)
      actionpack (= 4.2.5)
      activesupport (= 4.2.5)
      rake (>= 0.8.7)
      thor (>= 0.18.1, < 2.0)
    raindrops (0.15.0)
    rake (10.4.2)
    rb-fsevent (0.9.6)
    rb-inotify (0.9.5)
      ffi (>= 0.5.0)
    rdoc (4.2.0)
      json (~> 1.4)
    ref (2.0.0)
    refinerycms-acts-as-indexed (2.0.1)
      acts_as_indexed (~> 0.8.0)
      decorators (~> 2.0.0)
      refinerycms-core (~> 3.0.0)
    refinerycms-authentication-devise (1.0.4)
      actionmailer (~> 4.2, >= 4.2.0)
      devise (~> 3.0, >= 3.2.4)
      friendly_id (~> 5.1.0)
      refinerycms-core (~> 3.0, >= 3.0.0)
    refinerycms-i18n (3.0.1)
      rails-i18n (~> 4.0.1)
      routing-filter (>= 0.4.0)
    refinerycms-settings (3.0.0)
      friendly_id (~> 5.0, >= 5.0.1)
      refinerycms-core (~> 3.0, >= 3.0.0)
    refinerycms-wymeditor (1.0.6)
      refinerycms-core (~> 3.0, >= 3.0.0)
    responders (2.1.0)
      railties (>= 4.2.0, < 5)
    routing-filter (0.5.1)
      actionpack (~> 4.2)
      activesupport (~> 4.2)
    sass (3.4.20)
    sass-rails (5.0.4)
      railties (>= 4.0.0, < 5.0)
      sass (~> 3.1)
      sprockets (>= 2.8, < 4.0)
      sprockets-rails (>= 2.0, < 4.0)
      tilt (>= 1.1, < 3)
    sdoc (0.4.1)
      json (~> 1.7, >= 1.7.7)
      rdoc (~> 4.0)
    seo_meta (2.0.0.rc.1)
      railties (>= 3.0.0)
    sextant (0.2.4)
      rails (>= 3.2)
    shellany (0.0.1)
    slop (3.6.0)
    speakingurl-rails (1.1.5)
      railties (>= 3.1)
    spring (1.5.0)
    sprockets (3.5.2)
      concurrent-ruby (~> 1.0)
      rack (> 1, < 3)
    sprockets-rails (2.3.3)
      actionpack (>= 3.0)
      activesupport (>= 3.0)
      sprockets (>= 2.8, < 4.0)
    therubyracer (0.12.2)
      libv8 (~> 3.16.14.0)
      ref
    thor (0.19.1)
    thread_safe (0.3.5)
    tilt (2.0.1)
    truncate_html (0.9.3)
    turbolinks (2.5.3)
      coffee-rails
    tzinfo (1.2.2)
      thread_safe (~> 0.1)
    uglifier (2.7.2)
      execjs (>= 0.3.0)
      json (>= 1.8.0)
    unf (0.1.4)
      unf_ext
    unf_ext (0.0.7.1)
    unicorn (5.0.1)
      kgio (~> 2.6)
      rack
      raindrops (~> 0.7)
    warden (1.2.4)
      rack (>= 1.0)
    web-console (2.2.1)
      activemodel (>= 4.0)
      binding_of_caller (>= 0.7.2)
      railties (>= 4.0)
      sprockets-rails (>= 2.0, < 4.0)
    whenever (0.9.4)
      chronic (>= 0.6.3)
    will_paginate (3.0.7)
    xml-simple (1.1.5)
    zilch-authorisation (0.0.1)

PLATFORMS
  ruby

DEPENDENCIES
  actionpack-page_caching
  asset_sync
  aws-sdk (>= 2.0.0)
  bootstrap-sass (~> 3.3.5)
  byebug
  coffee-rails (~> 4.1.0)
  dalli
  dragonfly-s3_data_store
  figaro
  fog
  font-awesome-rails
  guard (>= 2.2.2)
  guard-livereload
  heroku-deflater
  jbuilder (~> 2.0)
  jquery-rails
  jquery-turbolinks
  kgio
  letter_opener
  memcachier
  paperclip
  pg
  quiet_assets
  rack-cache
  rack-livereload
  rails (~> 4.2.4)
  rails_12factor
  rails_on_heroku
  rb-fsevent
  refinerycms!
  refinerycms-acts-as-indexed (~> 2.0, >= 2.0.0)
  refinerycms-authentication-devise (~> 1.0)
  refinerycms-news!
  refinerycms-wymeditor (~> 1.0, >= 1.0.6)
  sass-rails (~> 5.0)
  sdoc (~> 0.4.0)
  sextant
  spring
  therubyracer (~> 0.12.1)
  turbolinks
  uglifier (>= 1.3.0)
  unf
  unicorn
  web-console (~> 2.0)
  whenever

BUNDLED WITH
   1.10.6

**Comment by bricesanchez** [comment]
This is your `Gemfile`. i need your `Gemfile.lock` to verify at which commit ref your are.

**Comment by bricesanchez** [comment]
What happens if your remove this line ?
```<li><%= link_to_if Globalize.locale.to_s != locale.to_s, locale, {:locale => locale} %></li>```

**Comment by imidsac** [comment]
if I delete the link, his walk.

**Comment by imidsac** [comment]
I want three languages, French, English and Arabic.

**Comment by bricesanchez** [comment]
So your problem is probably more your locale switcher in frontend than the refinerycms-news gem.

Could you try something like this instead ? 

```ruby
<div id="translations-menu">
  <% Refinery::I18n.config.frontend_locales.each do |l| %>
    <% unless I18n.locale == l %>
      <%= lang_switch_url l %>
    <% end %>
  <% end %>
</div>
```
```ruby
# app/helpers/application_helper.rb
  def lang_switch_url(l)
    Globalize.with_locale(l) do
      if @page
        url = refinery.url_for(@page.url)
      else
        url = root_path
      end

      return link_to Refinery::I18n.config.locales[l], url, hreflang: l
    end
```

**Comment by imidsac** [comment]
Good job, thank you very much.

**Comment by bricesanchez** [comment]
You're welcome!
