### ISSUE TITLE
Change the default news route

### ISSUE THREAD

**Issue by Pjero** [refinery/refinerycms-news#162]
Is it possible to change the routes "/news" "news/title" to a custom route like "/something-else" "/something-else/title"?
For example the Inquiries extension has that nicely solved in a .rb config file.

I am using the latest master branch version and I hope I didn't missed a trivial solution to this issue :).

**Comment by bricesanchez** [comment]
It's a missing feature, you could develop it or use refinerycms-blog who have this feature : https://github.com/refinery/refinerycms-blog
