### ISSUE TITLE
compatibility issue in friendly_id gem when use with refinerycms in rails4

### ISSUE THREAD

**Issue by AlbaHoo** [refinery/refinerycms-news#165]
I use rails 4.2 and refinerycms 3.0.3, when i try to add gem refinerycms-news 2.1.0, the friendly_id gem is 4.?.? in refinerycms-news while refinerycms require 5.?.?, I think  refinerycms-news is out-to-date, how can i fix that!

**Comment by bricesanchez** [comment]
You could use the github source instead rubygems source in waiting a new release : 

```ruby
gem 'refinerycms-news', github: 'refinery/refinerycms-news', branch: 'master'
```

**Comment by AlbaHoo** [comment]
Thanks you for the update, I have ended up use refinery engine to create my own news, works just fine. I will try your solution for my blog session.

**Comment by bricesanchez** [comment]
You're welcome.

Just in case `refinerycms-blog` has more features than news.
