### ISSUE TITLE
After restart, News in admin area drops 404

### ISSUE THREAD

**Issue by bertalanimre** [refinery/refinerycms-news#166]
I've inherited a server with a ruby website and refinery CMS including News plugin.
There was a system restart for the server and tho the website came back online, when someone goes to the admin area and tries to go to the news tab, all he can see is a 404 error message.
Any idea what could go wrong?

**Comment by bricesanchez** [comment]
Hello,

We need more informations to be able to fix the problem such as :
*  Could you copy/paste your Gemfile.lock ?
*  Do you have a step by step to reproduce?
*  Do you have an error stracktrace to share?

Thanks!

**Comment by bertalanimre** [comment]
Thank you for the reply, it turned out to be a user error, the user messed up something uploading a news and it broke the plugin. Removing the corresponding news from database solved the issue.

**Comment by bricesanchez** [comment]
Nice :)
